# vegetables, fruits, grains, dairy, meat & poultry, spices & seasonings,

vegetables = [
    "Artichoke", "Asparagus", "Avocado", "Bamboo shoots", "Beetroot", "Bell pepper", "Bitter melon", "Broccoli", 
    "Brussels sprouts", "Butternut squash", "Cabbage", "Carrot", "Cauliflower", "Celery", "Chard", "Chili pepper", 
    "Cucumber", "Daikon", "Eggplant", "Fennel", "Green beans", "Jalapeño", "Kale", "Leek", "Lettuce", "Mushrooms", 
    "Okra", "Onion", "Parsnip", "Peas", "Potato", "Pumpkin", "Radish", "Rhubarb", "Spinach", "Sweet potato", "Tomato", 
    "Turnip", "Watercress", "Zucchini", "Napa cabbage", "Chinese cabbage", "Kohlrabi", "Celeriac", "Chili flakes", 
    "Chili powder", "Garlic", "Shallots", "Scallions", "Taro root", "Yam", "Fiddlehead ferns", "Coriander", "Bok choy", 
    "Chives", "Water chestnut", "Leeks", "Ginger", "Chili oil", "Sprouts", "Alfalfa sprouts", "Cabbage leaf", "Oregano", 
    "Cress", "Jicama", "Celery root", "Mache", "Dandelion greens", "Mustard greens", "Swiss chard", "Radicchio", "Nettle", 
    "Fennel fronds", "Chicory", "Collard greens", "Moringa", "Endive", "Mizuna", "Romaine lettuce", "Sorrel", "Fava beans", 
    "Mung beans", "Soybean", "Cabbage leaves", "Pumpkin leaves", "Zucchini blossoms", "Curry leaves", "Cassava", "Upland cress", 
    "Chayote", "Amaranth", "Tat soi", "Taro", "Garbanzo beans", "Chickpeas", "Bamboo shoots", "Kale sprouts", "Chili pepper paste", 
    "Shiso", "Seaweed", "Cucumber leaf", "Tatsoi", "Chili bean paste", "Iceberg lettuce", "Chili bean sauce", "Salicornia", 
    "Okra pods", "Brussels sprouts leaves", "Pickled ginger", "Yard-long bean", "Romanescu", "Jalapeno pepper", "Wasabi root", 
    "Curry leaf", "Sorrel leaves", "Fennel bulb", "Kale chips", "Cucumber flower", "Leek stalks", "Fennel seeds", "Sweet corn", 
    "Tomatillo", "Nori", "Shallot leaves", "Gherkin", "Chili pepper flakes", "Jerusalem artichoke", "Purple yam", "Cardoon", 
    "Water spinach", "Pumpkin blossoms", "Chili oil sauce", "Lima beans", "Kohlrabi greens", "Lima bean sprouts", "Sweet corn kernels", 
    "Bitter gourd", "Rutabaga", "Taro leaves", "Fennel stems", "Sweet potato leaves", "Celosia", "Maitake mushrooms", "Pomelo", 
    "Patty pan squash", "Plum tomatoes", "Burdock root", "Portobello mushroom", "Herb thyme", "Root vegetables", "Purslane", 
    "Chili oil", "Fennel root", "Chili pepper oil", "Celeriac root", "Lotus root", "Sprouts of various plants", "Cress shoots", 
    "Chicory roots", "Tamarillo", "Moringa leaves", "Radicchio leaves", "Ramps", "Crosnes", "Sugar snap peas", "Okra flower", 
    "Watermelon radish", "Celosia flowers", "Pea shoots", "Water spinach shoots", "Chinese spinach", "Spinach flower", "Fennel root", 
    "Taro tubers", "Indian mustard", "Jalapeño pepper pods", "Chili pepper pods", "Sweet basil", "Pepper leaf", "Taro rootlets", 
    "Wild mustard", "Zucchini leaves", "Eggplant flowers", "Spinach stems", "Cucumber slices", "Kale leaflets", "Mint leaf", 
    "Kale veins", "Lettuce stalks", "Yam stems", "Snow peas", "Wakame", "Spinach root", "Lotus rootlets", "Daikon shoots", 
    "Chili stalks", "Ginger stalks", "Garlic shoots", "Green chili stalks", "Paprika leaves", "Bean sprouts", "Paprika flower", 
    "Chili flower", "Pennywort", "Kale roots", "Mushroom stems", "Garlic rootlets", "Edible flowers", "Garlic scapes", "Scallion roots",
    "Pumpkin seeds", "Cucumber peel", "Corn stalk", "Corn husks", "Kale blossoms", "Tomato vine", "Mushroom caps", "Kohlrabi pods", 
    "Rutabaga stems", "Ginger rootlets", "Cabbage stems", "Sweet potato stems", "Tomato stems", "Pepper flowers", "Spicy sprouts", 
    "Bamboo leaves", "Peppercorn", "Fennel flowers", "Fresh ginger root", "Sweet basil leaves", "Squash blossoms", "Radish sprouts", 
    "Cucumber flowers", "Potato stems", "Chili peppers seeds", "Potato sprouts", "Wheatgrass", "Garlic cloves", "Chili pepper stalks",
    "Ginger flowers", "Hot chili peppers", "Tomato blossoms", "Beetroot stems", "Sweet potato vines", "Sweet corn cobs", "Dandelion root", 
    "Ginger leaves", "Wasabi leaves", "Sweet basil stalks", "Daikon roots", "Yellow pumpkin", "Rice shoots", "Yam flowers", 
    "Nasturtium leaves", "Paprika stalks", "Chili paste", "Eggplant roots", "Bean sprouts", "Cilantro", "Taro stem", "Chickpea pods", 
    "Fennel bulb", "Dandelion greens", "Tatsoi greens", "Water spinach flowers", "Sesame leaves", "Pickled vegetables", "Cucumber seeds",
    "Chard leaves", "Chili oil sauce", "Green pepper", "Plum tomatoes", "Spring onion", "Leek pods", "Basil leaves", "Rutabaga roots", 
    "Pumpkin flowers", "Squash flowers", "Kohlrabi flowers", "Yellow squash", "Yellow bell pepper", "Napa cabbage flowers", 
    "Oregano leaves", "Fennel flower stalks", "Cabbage roots", "Mushroom roots", "Carrot greens", "Sugar snap peas"
]


fruits = [
    "Apple", "Banana", "Orange", "Strawberry", "Grape", "Blueberry", "Pineapple", "Peach", "Pear", "Mango",
    "Watermelon", "Papaya", "Plum", "Apricot", "Raspberry", "Blackberry", "Kiwi", "Pomegranate", "Cherry", "Lemon",
    "Lime", "Grapefruit", "Cantaloupe", "Honeydew", "Fig", "Dragonfruit", "Passionfruit", "Tangerine", "Mandarin",
    "Nectarine", "Lychee", "Starfruit", "Jackfruit", "Avocado", "Guava", "Coconut", "Cranberry", "Tamarind", "Mulberry",
    "Durian", "Raisin", "Date", "Olive", "Persimmon", "Longan", "Soursop", "Gooseberry", "Jambolan", "Clementine",
    "Pomelo", "Currant", "Blood Orange", "Fuyu Persimmon", "Jackfruit", "Cranberry", "Sea Buckthorn", "Tamarillo", 
    "Cape Gooseberry", "Zucchini", "Cucumber", "Carambola", "Red Grapes", "Golden Apple", "Soursop", "Indian Fig",
    "Miracle Fruit", "Coconut Water", "Cranberry", "Blackcurrant", "Kumquat", "Rhubarb", "Acerola", "Marula", "Marula",
    "Goji Berry", "Acai Berry", "Mulberry", "Blackberry", "Yunnan Hackberry", "Jujube", "Yunnan Plum", "Red Currant", 
    "Tamarillo", "Litchi", "Cloudberry", "Sea Buckthorn", "Figs", "Nance", "Guaraná", "Salak", "Buddha’s Hand", 
    "Blood Lime", "Mamey", "Satsuma", "Sapodilla", "Genip", "Elderberry", "Lingonberry", "Quince", "Sugar Apple", 
    "Rose Apple", "Bittermelon", "Chayote", "Sweetsop", "Yunnan Pineapple", "Chikoo", "Mango Steen", "Black Elderberry", 
    "Pineberry", "Avocado Pear", "Cranberry Pear", "Honeycrisp Apple", "Cotton Fruit", "Tamarind Pods", "Surinam Cherry", 
    "Ackee", "Warty Squash", "Chilean Guava", "Chinese Lychee", "Star Apple", "Indian Custard Apple", "Inga Fruit", 
    "Baobab", "Orange Pineapple", "Tuna Fruit", "Spiny Fruit", "Rattan Fruit", "Clementine", "Jatropha Fruit", "Pink Banana", 
    "Gala Apple", "Macadamia Nut", "Pineapple Guava", "Citrus Fruits", "Sour Cherry", "Lemon Plum", "Pineapple Guava", 
    "Pears", "Golden Pear", "Dewberry", "Tropical Fruits", "Hawthorn Berries", "Wild Blackberry", "Kiwifruit", 
    "Tropical Berry", "Wild Raspberry", "Strawberry Guava", "Papaya Melon", "Honeydew Melon", "Indian Fig Fruit", 
    "Green Apple", "Sunberry", "Indian gooseberry", "Kiwi berry", "Indian Almond", "Mango Peel", "Banana Peel", 
    "Chilean Berry", "Black Persimmon", "Red Apple", "Persimmon Plums", "Yellow Banana", "Green Plum", "Wild Mango", 
    "Orange Mamey", "Carrot Fruit", "Peach fruit", "Watermelon fruits", "Guarana Fruit", "Jasmine Fruit", "Orange Honey",
    "Thai Mango", "Papaya Red", "Tropical Avocado", "Peach Melon", "Avocado Flower", "Tamarillo Tree", "Green Gooseberry",
    "Plum Tree", "Goji Fruit", "Mangosteen Fruit", "Dragonfruit Tree", "Prickly Pear", "Pineapple Plant", "Hawaii Pineapple",
    "Yellow Cherry", "Fruit Salad", "Purple Passion Fruit", "Soursop Tree", "Orange Fleshed Papaya", "Sugar Cane", 
    "Jackfruit Tree", "Tropical Citrus", "Green Lemon", "Blue Tomato", "Lemon Verbena", "Papaya Seed", "Tropical Fruits",
    "Watermelon Slice", "Dried Pear", "Dried Grape", "Frozen Fruits", "Green Papaya", "Purple Mangosteen", "Pineapple Spear",
    "Ginger Fruits", "Orange Segment", "Frozen Mango", "Lemon Rind", "Peach Slice", "Mandarin Fruit", "Tamarind Pulp", 
    "Carambola Fruit", "Pink Guava", "Dried Mango", "Guava Leaves", "Papaya Flesh", "Fruit Tarts", "Pineapple Leaves",
    "Banana Flowers", "Papaya Tree", "Raspberry Bush", "Mango Flower", "Watermelon Seeds", "Fruits of Trees", "Coconut Shell",
    "Avocado Trees", "Papaya Leaves", "Mangrove Fruits", "Wild Pineapple", "Tamarillo Skin", "Star Fruit Peels", "Peach Trees",
    "Tropical Lemon", "Papaya Pods", "Golden Tamarillo", "Green Guava", "Dragonfruit Seed", "Pineapple Roots", "Lemon Berries",
    "Grape Leaves", "Wild Lemons", "Mango Fruits", "Pineapple Seed", "Lychee Fruits", "Papaya Juice", "Wild Pear", "Lemon Flowers",
    "Orange Fruit", "Papaya Tree Leaves", "Apple Fruit", "Chilean Tamarillo", "Bitterfruit", "Wild Orange", "Apple Blossoms",
    "Mulberry Fruits", "Pineapple Berries", "Green Mango", "Guava Fruit", "Mango Slices", "Acerola Cherries", "Dried Figs",
    "Tropical Grapefruit", "Lemon Water", "Banana Pods", "Goji Berries", "Black Mango", "Blackcurrant Jam", "Raisin Pear", "Tamarillo Fruits"
]


grains = [
    "Rice", "Wheat", "Corn", "Barley", "Oats", "Quinoa", "Rye", "Millet", "Buckwheat", "Sorghum",
    "Spelt", "Teff", "Amaranth", "Farro", "Couscous", "Freekeh", "Brown rice", "White rice", "Black rice", 
    "Jasmine rice", "Basmati rice", "Arborio rice", "Wild rice", "Short-grain rice", "Medium-grain rice", 
    "Long-grain rice", "Red rice", "Purple rice", "Glutinous rice", "Job's tears", "Chia seeds", "Flaxseed", 
    "Sesame seeds", "Hemp seeds", "Sunflower seeds", "Poppy seeds", "Pumpkin seeds", "Fennel seeds", "Cumin seeds", 
    "Caraway seeds", "Mustard seeds", "Nigella seeds", "Safflower seeds", "Canola seeds", "Pine nuts", "Almonds", 
    "Walnuts", "Brazil nuts", "Cashews", "Hazelnuts", "Pistachios", "Macadamia nuts", "Peanuts", "Chestnuts", 
    "Soybeans", "Lentils", "Chickpeas", "Kidney beans", "Black beans", "Pinto beans", "Navy beans", "White beans", 
    "Fava beans", "Lima beans", "Green peas", "Snow peas", "Sugar snap peas", "Edamame", "Mung beans", "Split peas", 
    "Cannelini beans", "Adzuki beans", "Red beans", "Black-eyed peas", "Cowpeas", "Horse beans", "Chana dal", "Toor dal", 
    "Moong dal", "Masoor dal", "Urid dal", "Kalaadi dal", "Yellow peas", "Green gram", "Moth beans", "Broad beans", 
    "Garbanzos", "Anasazi beans", "Tepary beans", "Taro", "Cassava", "Arrowroot", "Sweet potato", "Yams", "Potatoes", 
    "Fennel", "Rice bran", "Wheat bran", "Cornmeal", "Corn flour", "Semolina", "Polenta", "Couscous", "Orzo", "Tapioca", 
    "Tapioca flour", "Rice flour", "Chickpea flour", "Besan", "Almond flour", "Coconut flour", "Sorghum flour", 
    "Millet flour", "Teff flour", "Oat flour", "Barley flour", "Rye flour", "Spelt flour", "Whole wheat flour", 
    "All-purpose flour", "Cake flour", "Bread flour", "Pastry flour", "Self-raising flour", "Gluten-free flour", 
    "Coconut meal", "Quinoa flour", "Lupin flour", "Brown rice flour", "Triticale", "Kamut", "Sacha Inchi", "Pulses", 
    "Faro", "Carnaroli rice", "Gluten-free pasta", "Rice noodles", "Shirataki noodles", "Udon", "Soba noodles", 
    "Rice paper", "Edamame noodles", "Konjac noodles", "Buckwheat noodles", "Glass noodles", "Chickpea pasta", 
    "Corn pasta", "Spelt pasta", "Millet pasta", "Brown rice pasta", "Quinoa pasta", "Lentil pasta", "Mung bean pasta", 
    "Sweet corn flour", "Kamut flour", "Amaranth flour", "Buckwheat flour", "Maize flour", "Tapioca starch", "Coconut starch", 
    "Banana flour", "Green pea flour", "Carob flour", "Wheatgrass powder", "Wheat berries", "Oat flakes", "Oatmeal", 
    "Puffed rice", "Rice cakes", "Rice crisps", "Puffed quinoa", "Puffed barley", "Puffed millet", "Puffed wheat", 
    "Rice grits", "Polenta grits", "Wheat germ", "Cornstarch", "Rice starch", "Arrowroot powder", "Tapioca pearls", 
    "Corn tortillas", "Rice tortillas", "Spelt tortillas", "Millet tortillas", "Quinoa tortillas", "Chia flour", 
    "Hemp flour", "Green pea flour", "Chia meal", "Amaranth seeds", "Teff seeds", "Sorghum seeds", "Wheatgrass", 
    "Oat bran", "Rice bran oil", "Soybean oil", "Corn oil", "Canola oil", "Peanut oil", "Sesame oil", "Sunflower oil", 
    "Olive oil", "Coconut oil", "Avocado oil", "Hemp seed oil", "Chia oil", "Flaxseed oil", "Pumpkin seed oil", 
    "Rice oil", "Almond oil", "Walnut oil", "Hazelnut oil", "Macadamia nut oil", "Safflower oil", "Grapeseed oil", 
    "Pistachio oil", "Coconut milk", "Almond milk", "Soy milk", "Oat milk", "Rice milk", "Hemp milk", "Cashew milk", 
    "Coconut yogurt", "Soy yogurt", "Oat yogurt", "Almond yogurt", "Peanut butter", "Almond butter", "Cashew butter", 
    "Sunflower butter", "Coconut butter", "Tahini", "Nutella", "Ghee", "Clarified butter", "Butter", "Margarine", 
    "Coconut cream", "Whipped cream", "Heavy cream", "Sour cream", "Cream cheese", "Ricotta", "Cottage cheese", "Mascarpone", 
    "Blue cheese", "Cheddar cheese", "Mozzarella", "Parmesan cheese", "Feta cheese", "Swiss cheese", "Brie cheese", 
    "Creamed cheese", "Halloumi", "Emmental", "Gruyère", "Goat cheese", "Ricotta cheese", "Paneer", "Taleggio", "Roquefort", 
    "Cotija", "Burrata", "Chèvre", "Provolone", "Fontina", "Romano", "Monterey Jack", "Pepper Jack", "Gouda", "Caciocavallo", 
    "Stilton", "Edam", "Queso blanco", "Bocconcini", "Kefir", "Yogurt", "Vegan cheese", "Tofu", "Tempeh", "Seitan", 
    "Textured vegetable protein", "Nutritional yeast", "Vegan butter", "Vegan cream cheese", "Vegan sour cream", "Soy protein", 
    "Tofu skins", "Pecan meal", "Peanut meal", "Almond meal", "Coconut flour", "Barley grass", "Oatmeal flour", "Chia powder",
    "Pumpkin powder", "Banana powder", "Squash powder", "Lentil powder", "Brown rice powder", "Amaranth powder", "Pea protein",
    "Fava powder", "Rice powder", "Sorghum powder", "Kamut powder", "Buckwheat powder", "Teff flour", "Oat protein", "Chia protein"
]


dairy = [
    "Milk", "Whole milk", "Skim milk", "Low-fat milk", "Almond milk", "Soy milk", "Coconut milk", "Rice milk", "Oat milk",
    "Goat milk", "Sheep milk", "Buffalo milk", "Heavy cream", "Whipping cream", "Sour cream", "Cream cheese", "Mascarpone",
    "Cottage cheese", "Ricotta", "Cheddar cheese", "Mozzarella", "Parmesan cheese", "Swiss cheese", "Brie cheese", "Feta cheese",
    "Blue cheese", "Provolone", "Emmental", "Gruyère", "Goat cheese", "Halloumi", "Gouda", "Camembert", "Roquefort", "Fontina",
    "Monterey Jack", "Pepper Jack", "Burrata", "Taleggio", "Stilton", "Ricotta cheese", "Queso blanco", "Cotija cheese", "Bocconcini",
    "Pecorino", "Manchego", "Cotija", "Tzatziki", "Kefir", "Yogurt", "Greek yogurt", "Skyr", "Lassi", "Buttermilk", "Sour milk",
    "Milk powder", "Condensed milk", "Evaporated milk", "Powdered milk", "Non-dairy creamer", "Vegan butter", "Vegan cheese",
    "Almond yogurt", "Soy yogurt", "Oat yogurt", "Coconut yogurt", "Cashew cheese", "Vegan sour cream", "Vegan milk", "Vegan cream",
    "Rice cream", "Tofu", "Tempeh", "Paneer", "Frozen yogurt", "Creamed cheese", "Whipped cream", "Butter", "Clarified butter",
    "Ghee", "Margarine", "Lactose-free milk", "Lactose-free cream", "Lactose-free butter", "Lactose-free yogurt", "Vegan cream cheese",
    "Kefir grains", "Whey protein", "Ricotta salata", "Mascarpone cheese", "Cottage cheese curds", "Cottage cheese with fruit", 
    "Cottage cheese with honey", "Sweetened condensed milk", "Non-fat Greek yogurt", "Non-fat yogurt", "Whole milk yogurt", 
    "Reduced-fat yogurt", "Milk kefir", "Yogurt drink", "Buttermilk powder", "Milk solids", "Butterfat", "Cheese curds", "Cheese powder", 
    "Cottage cheese dip", "Vegan margarine", "Coconut butter", "Flavored milk", "Milk shake", "Frozen custard", "Butter milkshake", 
    "Ice cream", "Gelato", "Frozen dessert", "Sundae", "Frozen yogurt mix", "Cheese spread", "Parmesan powder", "Blue cheese dressing",
    "Cheddar cheese powder", "Mozzarella sticks", "Fried cheese curds", "Cheese fondue", "Cheese dip", "Ricotta cheese filling", 
    "Ricotta cheese dumplings", "Queso dip", "Queso fresco", "Ricotta pancakes", "Baked cheese", "Feta crumbles", "Feta dip", "Ricotta cheesecake",
    "Gouda slices", "Brie slices", "Cheddar slices", "Cheese slices", "Feta cheese slices", "Swiss cheese slices", "Mozzarella balls",
    "Grated parmesan", "Grated cheddar", "Grated mozzarella", "Grated cheese", "Parmesan shavings", "Baked Brie", "Melted cheese", "Cheese balls",
    "Cream cheese frosting", "Buttercream", "Vegan butter", "Butter spread", "Butter blocks", "Butter bars", "Melted butter", "Milk foam", 
    "Sweetened condensed milk frosting", "Frozen butter", "Butter cubes", "Butter powder", "Frozen buttercream", "Coconut cream frosting", 
    "Whipped butter", "Clotted cream", "Clotted cream spread", "Raw milk", "Whole milk powder", "Whole fat milk", "Fresh cream", 
    "Butter for baking", "Buttermilk pancakes", "Malted milk powder", "Ghee spread", "Vegan cheese spread", "Plant-based butter", 
    "Vegan yogurt", "Soy-based yogurt", "Almond-based yogurt", "Coconut-based yogurt", "Cashew-based cheese", "Vegan mozzarella", 
    "Vegan feta", "Vegan cheddar", "Almond-based cream", "Coconut-based cream", "Vegan sour cream", "Coconut oil", "Sheep's milk yogurt", 
    "Almond-based milk", "Oat-based milk", "Soy-based milk", "Lactose-free butter", "Sour cream cheese dip", "Lactose-free cheese",
    "Lactose-free cream cheese", "Vegan buttercream", "Vegan milkshake", "Lactose-free ice cream", "Lactose-free yogurt drink", 
    "Non-dairy creamer powder", "Non-dairy whipped cream", "Vegan whipped cream", "Sour milk cheese", "Yogurt-based dressing", 
    "Yogurt-based dip", "Yogurt sauce", "Cheese sauce", "Melted cheese sauce", "Cheese-filled pastry", "Cheese-stuffed bread", 
    "Chèvre cheese", "Alfredo sauce", "Parmesan crusted cheese", "Pita with cheese", "Cheese cracker", "Milk tea", "Chocolate milk", 
    "Milkshake with ice cream", "Flavored milk powder", "Nut milk", "Coconut milk ice cream", "Almond butter", "Macadamia nut butter", 
    "Peanut butter", "Walnut butter", "Cashew butter", "Pistachio butter", "Tahini", "Sunflower seed butter", "Pumpkin seed butter",
    "Brazil nut butter", "Hazelnut butter", "Coconut butter", "Mango butter", "Flaxseed butter", "Macadamia nut milk", "Almond spread", 
    "Coconut spread", "Cashew cheese spread", "Almond flour butter", "Coconut milk spread", "Yogurt with honey", "Mango lassi", 
    "Buttermilk drink", "Ricotta dip", "Ricotta cheese spread", "Milk for baking", "Dairy-free cheese", "Butter substitute", 
    "Coconut milk substitute", "Vegan dairy products", "Lactose-free milk substitute", "Soy cheese", "Almond cheese", "Non-dairy spread",
    "Dairy-free spread", "Vegan yogurt spread", "Plant-based spread", "Dairy-based spread", "Cheese topping", "Yogurt topping", 
    "Coconut topping", "Vegan whipped topping", "Non-dairy yogurt topping", "Dairy whipped topping", "Non-dairy whipped topping", 
    "Vegan ice cream", "Vegan whipped topping", "Cheese topping for pizza", "Milk powder for tea", "Non-dairy milk powder", 
    "Non-dairy milk substitute", "Soy milk powder", "Almond milk powder", "Coconut milk powder", "Dairy substitute", "Plant milk",
    "Vegan dessert", "Vegan cheesecake", "Dairy-free frosting", "Dairy-free cake mix", "Vegan cream"
]


meat_poultry_items = [
    "Chicken", "Chicken breast", "Chicken thighs", "Chicken wings", "Chicken drumsticks", "Whole chicken", "Chicken tenders",
    "Chicken legs", "Chicken liver", "Chicken gizzards", "Turkey", "Turkey breast", "Turkey legs", "Ground turkey",
    "Duck", "Duck breast", "Duck legs", "Goose", "Goose breast", "Pigeon", "Quail", "Cornish hen", "Pheasant", "Squab",
    "Rabbit", "Rabbit legs", "Venison", "Venison steaks", "Venison roast", "Bison", "Bison steak", "Bison ground meat", "Beef",
    "Beef steak", "Beef ribs", "Beef roast", "Beef brisket", "Beef stew meat", "Ground beef", "Beef sirloin", "Beef tenderloin",
    "Beef flank", "Beef chuck", "Beef round", "Beef skirt steak", "Beef short ribs", "Beef liver", "Beef heart", "Beef tongue",
    "Beef kidney", "Beef oxtail", "Beef shank", "Beef chuck roast", "Pork", "Pork chops", "Pork ribs", "Pork loin", "Pork tenderloin",
    "Pork shoulder", "Pork belly", "Pork roast", "Ground pork", "Pork sausage", "Pork ham", "Pork hocks", "Pork feet", "Pork ears",
    "Pork jowls", "Pork loin roast", "Pork bacon", "Pork salami", "Pork sausage links", "Sausage", "Bratwurst", "Chorizo", "Andouille sausage",
    "Italian sausage", "Polska kielbasa", "Breakfast sausage", "Merguez", "Blood sausage", "Lamb", "Lamb chops", "Lamb leg",
    "Lamb rack", "Lamb shoulder", "Lamb stew meat", "Ground lamb", "Lamb tongue", "Lamb kidneys", "Lamb liver", "Lamb ribs",
    "Lamb shank", "Lamb belly", "Lamb meatballs", "Lamb sausages", "Lamb chops rack", "Lamb roast", "Goat", "Goat meat", "Goat stew",
    "Goat chops", "Goat leg", "Goat ribs", "Goat shoulder", "Goat stew meat", "Pork belly", "Pork feet", "Pork neck bones", "Pork belly strips",
    "Beef tongue", "Beef heart", "Beef cheek", "Beef short ribs", "Beef stew meat", "Ox tail", "Bison ribeye", "Pork scratchings", 
    "Bison burger", "Duck confit", "Lamb shawarma", "Venison steaks", "Pheasant legs", "Venison sausage", "Venison stew", "Wild boar",
    "Wild turkey", "Wild venison", "Buffalo steak", "Buffalo burger", "Buffalo ribs", "Ground buffalo", "Rabbit stew", "Rabbit sausage",
    "Chicken sausage", "Canned chicken", "Canned tuna", "Canned ham", "Canned turkey", "Canned salmon", "Beef jerky", "Pork jerky", 
    "Turkey jerky", "Chicken jerky", "Biltong", "Fish fillets", "Cod fillets", "Salmon fillets", "Tuna steaks", "Mahi-mahi", 
    "Halibut fillets", "Tilapia", "Catfish", "Swordfish", "Shrimp", "Lobster", "Crab", "Clams", "Oysters", "Scallops", "Mussels",
    "Squid", "Octopus", "Anchovies", "Smoked salmon", "Canned sardines", "Canned tuna fish", "Canned salmon", "Canned mackerel",
    "Canned clams", "Canned oysters", "Canned shrimp", "Canned anchovies", "Pork belly strips", "Oxtail stew", "Salami", "Pepperoni",
    "Prosciutto", "Coppa", "Bresaola", "Pastrami", "Pâté", "Rillettes", "Serrano ham", "Jamón ibérico", "Soppressata", "Pastrami",
    "Mortadella", "Country ham", "Turkey bacon", "Canned bacon", "Canned beef", "Canned sausage", "Chicken liver pate", "Turkey liver",
    "Beef liver", "Liverwurst", "Chopped liver", "Canned ham", "Turkey pastrami", "Brisket", "Prime rib", "Hanger steak", "Flank steak",
    "Sirloin steak", "T-bone steak", "Porterhouse steak", "New York strip", "Rib-eye steak", "Skirt steak", "Chuck steak", "Flat iron steak",
    "Filet mignon", "Shish kebab", "Steak tartare", "Beef stew", "Ground lamb", "Chicken kebabs", "Turkey meatballs", "Lamb kofta",
    "Lamb shank stew", "Bison burger patties", "Goat curry", "Venison chili", "Beef stew with vegetables", "Ground pork stir-fry", 
    "Venison steak sandwich", "Pork schnitzel", "Veal schnitzel", "Beef Wellington", "Lamb curry", "Lamb kofta kebabs", "Pork dumplings",
    "Ground turkey chili", "Chicken pot pie", "Chicken alfredo", "Chicken fried rice", "Chicken curry", "Turkey meatloaf", "Chicken nuggets",
    "Bacon-wrapped chicken", "Stuffed turkey", "Chicken parmesan", "Turkey burgers", "Chicken shawarma", "Lamb biryani", "Beef and rice",
    "Pork tacos", "Beef tacos", "Chicken fajitas", "Pork tamales", "Grilled turkey breast", "Grilled lamb chops", "BBQ chicken", 
    "Roast duck", "BBQ ribs", "Braised beef", "Fried chicken", "Duck à l'orange", "Grilled rabbit", "Roast lamb", "Beef roast", 
    "Roast goose", "Stuffed quail", "Goose confit", "Spicy sausage", "Pork roast", "Lamb stew", "Beef kebabs", "Pork fried rice", 
    "Lamb shank braised", "Grilled turkey legs", "Crispy chicken wings", "Bison stew", "Ground chicken", "Lamb stew meat", 
    "Chorizo sausage", "Merguez sausage", "Andouille sausage", "Salami", "Fried chicken wings", "Chicken drumstick", "Lamb cutlets", 
    "Pork sausages", "Chicken burger", "Pork tenderloin", "Duck fat", "Beef mince", "Beef meatballs", "Lamb meatballs", "Goat meatballs",
    "Pork cutlets", "Goose fat", "Goat stew", "Pork brisket", "Pork ribs with BBQ sauce", "Lamb shank curry", "Venison stew meat", 
    "Bison steak grilled", "Pork belly roasted", "Chicken tikka", "Goat meat curry", "Rabbit stew", "Duck stew", "Pork belly braised",
    "Roast beef sandwich", "Turkey club sandwich", "Chicken sandwich", "Bacon sandwich", "Pork sandwich", "BBQ chicken wings", 
    "Grilled beef steaks", "Grilled lamb ribs", "Pork loin roast", "BBQ turkey", "Duck breast grilled", "Rabbit leg roast", 
    "Lamb chops grilled", "Venison fillet", "Turkey wings roasted", "Goose roast", "Stuffed chicken breasts", "Lamb kebabs", 
    "Pork ribs barbecued", "Grilled turkey burger", "Duck liver pate", "Grilled bison burger", "Beef burger", "Lamb burgers", 
    "Venison burger", "Duck confit salad", "Chickpea and chicken stew", "Pork stir-fry", "Beef stir-fry", "Ground turkey casserole", 
    "Chicken curry rice", "Chicken kebabs grilled", "Roast venison", "Grilled chicken breast", "Pork stir-fry", "Turkey stew"
]




print(len(vegetables))
print(len(ingredients2))
